CHECK_NOT_APPLICABLE = -1
CHECK_FALSE, CHECK_DEFAULT = 0, 0
CHECK_TRUE = 1
CHECK_RESULT_HIDDEN = 2
CHECK_RESULT_SUB = 3
CHECK_RESULT_UNCERTAIN = 4
CHECK_GENERAL_ERROR = 255

class ScrutinizeException(Exception):
    pass
